platform :ios, '7.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'


target 'iosapp' do

pod 'AFOnoResponseSerializer' , '~>1.0.0'
pod 'SDWebImage' , '~>3.8.1'
pod 'SSKeychain'
pod 'ReactiveCocoa'
pod 'GPUImage'
pod 'YYKit'
pod 'MBProgressHUD' , '~> 1.0.0'
pod 'Reachability'
pod 'TTTAttributedLabel'
pod 'GRMustache'
pod 'MJRefresh' , '~>3.1.10'
pod 'TBXML'
pod 'DateTools'
pod 'DTCoreText'
pod 'MJExtension' , '~>3.0.11'
pod 'UMengSocial' , '~>5.0'
pod 'UMengAnalytics-NO-IDFA' , '~> 4.0.5'
pod 'Myhpple'
pod 'Masonry'
pod 'TZImagePickerController'
pod 'MLeaksFinder'

end
